name = "sustainabox"
type = "javascript"
compatibility_date = "2024-12-16"

[site]
bucket = "./dist"

[[routes]]
pattern = "sustainabox.org"
zone_name = "sustainabox.org"

[[routes]]
pattern = "www.sustainabox.org"
zone_name = "sustainabox.org"
